### ISSUE TITLE
More CLI options

### ISSUE THREAD

**Issue by jayantbh** [Shuttl-Tech/terrace.js#6]
A bunch of CLI options for mentioned commands that could be introduced sooner or later.

- Create Project
  - [x] Config (to override .terrace-cli values on project creation) (think along the lines of git global config)
  - [x] No translate stuff built in

- Views and components
  - [x] Redux connected by default
  - [x] No named export
  - [x] No translate stuff built in
  - [x] Stateless (components only)

- Mocks
  - No new options ideas yet
- Remove
  - No new options ideas yet

**Comment by jayantbh** [comment]
Will reopen when new ideas come.
